-- ================================================================
-- SGHS SOL Prep — DSM Migration: Dynamic Study Modules
-- Run this in Supabase SQL Editor.
-- ================================================================

-- ── DSM MODULES ────────────────────────────────────────────────
-- One row per published question set. A teacher generates questions
-- for a standard (e.g., BIO.3) and publishes them for students.
CREATE TABLE dsm_modules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  class_id UUID REFERENCES classes(id) ON DELETE CASCADE,  -- NULL = available to all teacher's classes
  standard TEXT NOT NULL,              -- 'BIO.1' through 'BIO.8'
  unit_number INTEGER NOT NULL,        -- 1-8
  title TEXT,                          -- optional custom title
  question_count INTEGER NOT NULL DEFAULT 25,
  status TEXT NOT NULL DEFAULT 'draft', -- 'draft' or 'published'
  created_by UUID REFERENCES teachers(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_dsm_modules_standard ON dsm_modules(standard);
CREATE INDEX idx_dsm_modules_status ON dsm_modules(status);
CREATE INDEX idx_dsm_modules_teacher ON dsm_modules(created_by);

-- ── DSM QUESTIONS ──────────────────────────────────────────────
-- Individual questions within a module (AI-generated by Gemini).
CREATE TABLE dsm_questions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  module_id UUID NOT NULL REFERENCES dsm_modules(id) ON DELETE CASCADE,
  question_text TEXT NOT NULL,
  option_a TEXT NOT NULL,
  option_b TEXT NOT NULL,
  option_c TEXT NOT NULL,
  option_d TEXT NOT NULL,
  correct_answer TEXT NOT NULL,         -- 'a', 'b', 'c', or 'd'
  explanation TEXT NOT NULL,
  difficulty TEXT DEFAULT 'medium',     -- 'easy', 'medium', 'hard'
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_dsm_questions_module ON dsm_questions(module_id);

-- ── DSM ATTEMPTS ───────────────────────────────────────────────
-- Tracks each student's attempt at completing a DSM.
CREATE TABLE dsm_attempts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  class_id UUID NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  student_name TEXT NOT NULL,
  module_id UUID NOT NULL REFERENCES dsm_modules(id) ON DELETE CASCADE,
  unit_number INTEGER NOT NULL,
  rounds_completed INTEGER NOT NULL DEFAULT 0,
  total_questions INTEGER NOT NULL,
  questions_missed JSONB DEFAULT '[]',  -- array of { round, questionId, questionText }
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ
);

CREATE INDEX idx_dsm_attempts_student ON dsm_attempts(class_id, student_name);
CREATE INDEX idx_dsm_attempts_module ON dsm_attempts(module_id);

-- ── ROW LEVEL SECURITY ─────────────────────────────────────────
ALTER TABLE dsm_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE dsm_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE dsm_attempts ENABLE ROW LEVEL SECURITY;

-- Students (anon) can read published modules
CREATE POLICY "Anyone can read published DSM modules"
  ON dsm_modules FOR SELECT
  USING (status = 'published');

-- Students can read questions of published modules
CREATE POLICY "Anyone can read published DSM questions"
  ON dsm_questions FOR SELECT
  USING (
    is_active = TRUE
    AND module_id IN (SELECT id FROM dsm_modules WHERE status = 'published')
  );

-- Students can create and update their own attempts
CREATE POLICY "Students can create DSM attempts"
  ON dsm_attempts FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Students can update DSM attempts"
  ON dsm_attempts FOR UPDATE
  USING (true);

-- Teachers can manage their own modules (CRUD)
CREATE POLICY "Teachers manage own DSM modules"
  ON dsm_modules FOR SELECT
  USING (created_by = get_teacher_id() OR is_admin());

CREATE POLICY "Teachers insert DSM modules"
  ON dsm_modules FOR INSERT
  WITH CHECK (created_by = get_teacher_id() OR is_admin());

CREATE POLICY "Teachers update own DSM modules"
  ON dsm_modules FOR UPDATE
  USING (created_by = get_teacher_id() OR is_admin());

CREATE POLICY "Teachers delete own DSM modules"
  ON dsm_modules FOR DELETE
  USING (created_by = get_teacher_id() OR is_admin());

-- Teachers can manage questions in their modules
CREATE POLICY "Teachers manage own DSM questions"
  ON dsm_questions FOR SELECT
  USING (
    module_id IN (SELECT id FROM dsm_modules WHERE created_by = get_teacher_id())
    OR is_admin()
  );

CREATE POLICY "Teachers insert DSM questions"
  ON dsm_questions FOR INSERT
  WITH CHECK (
    module_id IN (SELECT id FROM dsm_modules WHERE created_by = get_teacher_id())
    OR is_admin()
  );

CREATE POLICY "Teachers update own DSM questions"
  ON dsm_questions FOR UPDATE
  USING (
    module_id IN (SELECT id FROM dsm_modules WHERE created_by = get_teacher_id())
    OR is_admin()
  );

CREATE POLICY "Teachers delete own DSM questions"
  ON dsm_questions FOR DELETE
  USING (
    module_id IN (SELECT id FROM dsm_modules WHERE created_by = get_teacher_id())
    OR is_admin()
  );

-- Teachers can read attempts for their classes
CREATE POLICY "Teachers read own class DSM attempts"
  ON dsm_attempts FOR SELECT
  USING (class_id IN (SELECT get_my_class_ids()));
